server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  super-admin-paths: #RUTA DE ACCESO PARA SUPER ADMINISTRADOR
    paths:
      - uri: "/user"
        method: "POST"
      - uri: "/user/savecar/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/user/savebike/{1}[1-9]+[0-9]*"
        method: "POST"
  agente-support-paths: #RUTA DE ACCESO PARA AGENTE DE SOPORTE
    paths:
      - uri: "/user"
        method: "POST"
      - uri: "/user/savecar/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/user/savebike/{1}[1-9]+[0-9]*"
        method: "POST"
  supervisor-support-paths: #RUTA DE ACCESO PARA SUPERVISOR DE SOPORTE
    paths:
      - uri: "/user"
        method: "POST"
      - uri: "/user/savecar/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/user/savebike/{1}[1-9]+[0-9]*"
        method: "POST"
  user-admin-paths: #RUTA DE ACCESO PARA ADMINISTRADOR DE USUARIOS
    paths:
      - uri: "/user"
        method: "POST"
      - uri: "/user/savecar/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/user/savebike/{1}[1-9]+[0-9]*"
        method: "POST"
  user-paths: #RUTA DE ACCESO PARA USUARIO
    paths:
      - uri: "/user"
        method: "POST"
      - uri: "/user/savecar/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/user/savebike/{1}[1-9]+[0-9]*"
        method: "POST"
        
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          quitwait: false
          starttls:
            enabled: true
            required: true
