server:
  port: 8083
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    peer-node-read-timeout-ms: 1000

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/**
        - id: support-service
          uri: lb://SUPPORT-SERVICE
          predicates:
            - Path=/**
        - id: operations-service
          uri: lb://OPERATIONS-SERVICE
          predicates:
            - Path=/**