server:
  port: 8083
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            - Path=/user/**
        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/support/**
        - id: operations-service
          uri: lb://operations-service
          predicates:
            - Path=/operations/**