package colombia.authservice.Utils;

public enum EnumAcciones {
    ACTIVADO, // USUARIO ACTIVO
    BLOQUEADO, // USUARIO BLOQUEADO
    EMAIL, // CORREO VERIFICADO
    TELEFONO, // TELEFONO VERIFICADO
    HABILITADO, // USUARIO HABILITADO
}
