package colombia.supportservice.Utils;

public enum EnumOperacion {
    LISTAR, // ERROR AL LISTAR 
    CONSULTAR, //ERROR AL CONSULTAR
    GUARDAR, //ERROR AL GUARDAR
    EDITAR, //ERROR AL EDITAR
    ACCIONES, //ERROR AL EDITAR
    MODIFICAR, //ERROR EDITAR O GUARDAR
    LOGIN, // ERROR DE INICIO DE SESIÓN
    VALIDACION, // ERROR DE VALIDACIÓN DE DATOS
    OTROS,
    TOKEN
}
